### ISSUE TITLE
Read mysqldump

### ISSUE THREAD

**Issue by matinnuhamunada** [duckdb/duckdb_mysql#2]
Is it possible to read a mysqldump file into DuckDB?

**Comment by szarnyasg** [comment]
@matinnuhamunada I don't think this is possible at the moment. Can you export to CSVs? With that, you can likely go a long way using the DuckDB CSV reader's automatic schema detection: https://duckdb.org/docs/data/csv/overview.html

**Comment by Mytherin** [comment]
This is out-of-scope for this extension in any case - although you could read `mysqldump` into MySQL, and then use this extension to transfer data from MySQL into DuckDB
