### ISSUE TITLE
Why is the GPL3.0 license instead of MIT license

### ISSUE THREAD

**Issue by qzbqzb** [duckdb/duckdb_mysql#20]
### What happens?

Why is the GPL3.0 license instead of MIT license？

### To Reproduce

mysql_scanner extension is licensed under GPL3.0，but all other extensions are licensed under MIT. Can MIT license also be used to mysql_scanner?

### OS:

windows

### MySQL Version:

5.7.30

### DuckDB Version:

0.9.2

### DuckDB Client:

java

### Full Name:

Tom

### Affiliation:

Strive

### Have you tried this on the latest `main` branch?

- [X] I agree

### Have you tried the steps to reproduce? Do they include all relevant data and configuration? Does the issue you report still appear there?

- [X] I agree

**Comment by Peng-Lei** [comment]
I have the same question. Why is the GPL3.0 license instead of MIT license. Could we change it to MIT license the more friendly. @Mytherin

**Comment by qzbqzb** [comment]
As we all known, mysql-connector is licensed by GPL2.0, but mariadb connector which is licensed by LGPL-2.1 is also been used to connect to mysql server, Could we use mariadb connector in mysql_scanner?

**Comment by szarnyasg** [comment]
Hi @qzbqzb and @Peng-Lei, the license was GPL only due to legacy reasons. We changed it now. Enjoy!
