### ISSUE TITLE
Feature: mysql_query (similar to postgres_query)

### ISSUE THREAD

**Issue by sertainly** [duckdb/duckdb_mysql#35]
If I understood correctly, there's a functionality in the `duckdb_postgres` extension named `postgres_query` that allows to send queries directly to the db/engine and get the result back, without duckdb doing its magic in between.

I'd love to see this for `mysql` as well, e.g. something like `mysql_query(attached_database::VARCHAR, query::VARCHAR)`.

I could imagine that this may be a low hanging fruit and provide tremendous value (at least to me 😊)

Thanks so much in advance.

---

> Background is that I have some join queries of big tables that run super quick within MySQL, but when setting `mysql_debug_show_queries` it appears that duckdb does a `SELECT x FROM` for each of them, which takes rather long in comparison

**Comment by sertainly** [comment]
@Mytherin Apologies for tagging you directly, I imagine you have a lot on your plate. Could you just give an indication of when / if someone may have the chance to give this a try?

- 🚀 days
- ❤️ weeks
- 🎉 months
- 👎 won't be done any time soon

Any answer is fine, but it gives me the chance to deal with it in other ways (e.g. polars).
 
Thanks so much for your efforts 🦆 .

**Comment by Mytherin** [comment]
Thanks for the suggestion - I agree this is a good idea. I'll try to have a look at implementing this in the coming weeks.

**Comment by sertainly** [comment]
Aah that sounds great, thanks a ton 😊 

And if you need someone to run a few test queries once it's ready, I'm happy to help.

**Comment by Mytherin** [comment]
I have a PR up for this here - https://github.com/duckdb/duckdb_mysql/pull/50

**Comment by Mytherin** [comment]
Implemented now in main

**Comment by sertainly** [comment]
Thanks so much for implementing 😊 This will really help me. I'll try it out today.
