### ISSUE TITLE
mysql passwords using env var or secrets manager

### ISSUE THREAD

**Issue by ededovic** [duckdb/duckdb_mysql#41]
I'm a huge fan of DuckDB and MySQL extension! Thank you very much for all your hard work. 

Is it possible to pass MySQL password via an environment variable or the secrets file, similar to how you have it for PostgreSQL or how you do it now for S3... via the secrets manager? The secrets manager would be the best alternative in case there are many database servers; set it once and forget about it.  The secretes manager can already list all existing set ups, making it easy to recall the connection name and use it.  

https://duckdb.org/docs/extensions/mysql#supported-operations
https://duckdb.org/2024/01/26/multi-database-support-in-duckdb.html

**Comment by Mytherin** [comment]
Thanks for the suggestion - I agree this would be a good feature

**Comment by Mytherin** [comment]
I have an implementation for reading from environment variables here - https://github.com/duckdb/duckdb_mysql/pull/52

**Comment by ededovic** [comment]
That is great. Can’t wait to try this out.

**Comment by Mytherin** [comment]
It's available now in the published version for v0.10.1 - see the [readme](https://github.com/duckdb/duckdb_mysql?tab=readme-ov-file#reading-data-from-mysql)

**Comment by ededovic** [comment]
This works! Love you guys.
